apiVersion: v1
kind: Service
metadata:
  name: pihole-service
  namespace: pihole
spec:
  selector:
    app: pihole
  ports:
    - port: 53
      targetPort: 53
  externalTrafficPolicy: Local
  type: LoadBalancer