name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set variables
      run: |
        VER=$(cat  ${{ github.workspace }}/VERSION)
        echo "VERSION=$VER" >> $GITHUB_ENV

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker buildx build --build-arg PIHOLE_VERSION=${{ env.VERSION }} --platform linux/arm/v7,linux/arm64/v8,linux/amd64 -t mmorales08/docker-pihole-unbound:${{ env.VERSION }} .